### ISSUE TITLE
Cannot update exercise from localhost

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#547]
I can update [this](https://zsebtanar-test.web.app/admin/exercise/edit/6DyMXWXEhB68PjLuktyW) exercise from the test server. However, when I try to do the same from localhost, I get the following error message:

```
{status: "error", statusCode: 500, message: "Exercise update error",…}
details: {code: 7, details: "Missing or insufficient permissions.", metadata: {internalRepr: {}, options: {}},…}
code: 7
details: "Missing or insufficient permissions."
metadata: {internalRepr: {}, options: {}}
note: "Exception occurred in retry method that was not classified as transient"
message: "Exercise update error"
status: "error"
statusCode: 500
```

**Comment by maxinteger** [comment]
@vektor8891 I could not reproduce it.
Please reopen this task if you can.

**Comment by vektor8891** [comment]
@maxinteger I cannot _not_ reproduce it :)

**Comment by vektor8891** [comment]
@maxinteger I get the same error when I want to activate/delete etc. exercise.

**Comment by vektor8891** [comment]
Firebase log:
```
13:57:28
W
function[api]
Google API requested!
   - URL: "https://oauth2.googleapis.com/token"
   - Be careful, this may be a production service.
13:57:28
I
function[api]
Exercise update error Error: 7 PERMISSION_DENIED: Missing or insufficient permissions.
13:57:28
I
function[api]
    at Object.callErrorFromStatus (/home/szabo/Git/zsebtanar-proto/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
13:57:28
I
function[api]
    at Object.onReceiveStatus (/home/szabo/Git/zsebtanar-proto/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
13:57:28
I
function[api]
    at Object.onReceiveStatus (/home/szabo/Git/zsebtanar-proto/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
13:57:28
I
function[api]
    at Object.onReceiveStatus (/home/szabo/Git/zsebtanar-proto/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
13:57:28
I
function[api]
    at /home/szabo/Git/zsebtanar-proto/node_modules/@grpc/grpc-js/build/src/call-stream.js:130:78
13:57:28
I
function[api]
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
13:57:28
I
function[api]
Caused by: Error
13:57:28
I
function[api]
    at WriteBatch.commit (/home/szabo/Git/zsebtanar-proto/node_modules/@google-cloud/firestore/build/src/write-batch.js:413:23)
13:57:28
I
function[api]
    at /home/szabo/Git/zsebtanar-proto/bin/functions/index.js:608:21
13:57:28
I
function[api]
    at Generator.next (<anonymous>)
13:57:28
I
function[api]
    at fulfilled (/home/szabo/Git/zsebtanar-proto/node_modules/tslib/tslib.js:112:62)
13:57:28
I
function[api]
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
13:57:28
I
function[api]
  code: 7,
13:57:28
I
function[api]
  details: 'Missing or insufficient permissions.',
13:57:28
I
function[api]
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
13:57:28
I
function[api]
  note: 'Exception occurred in retry method that was not classified as transient'
13:57:28
I
function[api]
} undefined
13:57:29
I
function[api]
Finished "api" in ~1s
```
