### ISSUE TITLE
Előnézet generátor elhasal

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#75]
A fő probléma, hogy a cloud function nem tudja elérni a file storage-et mert hiányoznak a jogosultságok. A szükséges json fájl már létezik, de valahogy be kellene rakni a firebase config-ba és abból kiolvasni amikor szükséges...

```
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Sign.sign (crypto.js:286:26)
    at Object.sign (/user_code/node_modules/@google-cloud/storage/node_modules/jwa/index.js:53:47)
    at Object.jwsSign [as sign] (/user_code/node_modules/@google-cloud/storage/node_modules/jws/lib/sign-stream.js:23:26)
    at GoogleToken._signJWT (/user_code/node_modules/@google-cloud/storage/node_modules/gtoken/lib/index.js:240:25)
    at GoogleToken._requestToken (/user_code/node_modules/@google-cloud/storage/node_modules/gtoken/lib/index.js:195:15)
    at handleJSONKey (/user_code/node_modules/@google-cloud/storage/node_modules/gtoken/lib/index.js:102:10)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
```

**Comment by maxinteger** [comment]
#111 hasonló és a fenti leírás már nem is teljesen aktuális így lezárom
