### ISSUE TITLE
Cicle build javítása

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#91]
```
 FAIL  test/component/generic/Button.spec.js
  ● Test suite failed to run

    test renderer is not available in production mode.
      
      at Object.<anonymous> (node_modules/react-test-renderer/index.js:4:9)
      at Object.<anonymous> (test/component/generic/Button.spec.js:3:26)
          at Generator.next (<anonymous>)
          at Promise (<anonymous>)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:125:13)
      at process.emit (events.js:213:7)
      at emit (internal/child_process.js:774:12)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by maxinteger** [comment]
és kész is
